Repository shibayan/appservice-acmebot, pull requests merged in 2020-12, with the labels that each got.

#252 Update to Durable Functions v2.4.0
  AppService.Acmebot/AppService.Acmebot.csproj
Labels: enhancement

#253 Publish package for win-x86 runtime only
  .github/workflows/publish.yml
Labels: enhancement

#254 Refactoring function implementation
  AppService.Acmebot/AppService.Acmebot.csproj
  AppService.Acmebot/Contracts/RetryStrategy.cs
  AppService.Acmebot/Functions/AddCertificate.cs
  AppService.Acmebot/Functions/GetResourceGroups.cs
  AppService.Acmebot/Functions/GetSites.cs
  AppService.Acmebot/Functions/ISharedActivity.cs
  AppService.Acmebot/Functions/PurgeCertificates.cs
  AppService.Acmebot/Functions/PurgeInstanceHistory.cs
  AppService.Acmebot/Functions/RenewCertificates.cs
  AppService.Acmebot/Functions/SharedActivity.cs
  AppService.Acmebot/Functions/SharedOrchestrator.cs
  AppService.Acmebot/Functions/StaticPage.cs
  AppService.Acmebot/Internal/AcmeProtocolClientFactory.cs
  AppService.Acmebot/Internal/AppAuthenticationTokenProvider.cs
  AppService.Acmebot/Internal/ApplicationVersionInitializer.cs
  AppService.Acmebot/Internal/AzureEnvironment.cs
  AppService.Acmebot/Internal/KuduClientFactory.cs
  AppService.Acmebot/Internal/Punycode.cs
  AppService.Acmebot/Internal/WebhookInvoker.cs
  AppService.Acmebot/Internal/WebhookLifeCycleNotification.cs
  AppService.Acmebot/Models/DnsNameItem.cs
  AppService.Acmebot/Models/GetSitesInformation.cs
  AppService.Acmebot/Models/ResourceGroupItem.cs
  AppService.Acmebot/Models/SiteItem.cs
  AppService.Acmebot/Models/SlotItem.cs
  AppService.Acmebot/RetriableActivityException.cs
  AppService.Acmebot/Startup.cs
  AppService.Acmebot/static/add-certificate.html
Labels: enhancement

#256 Update Vue.js 3.0
  AppService.Acmebot/static/add-certificate.html
Labels: enhancement

#258 Mitigated Azure REST API issue
  AppService.Acmebot/Internal/AzureSdkExtensions.cs
Labels: bug

#260 Improve README
  README.md
  docs/acmebot-diagram.svg
Labels: documentation
