Repository shibayan/appservice-acmebot, pull requests merged in 2020-08, with the labels that each got.

#203 Change to only renew certificates issued to the same endpoint
  AppService.Acmebot/SharedFunctions.cs
Labels: enhancement

#204 Update Deploy to Azure Button
  README.md
  README_ja.md
Labels: documentation

#205 Update README.md
  README.md
  README_ja.md
Labels: documentation

#206 Update certificate tags filtering
  .gitignore
  AppService.Acmebot/Contracts/ISharedFunctions.cs
  AppService.Acmebot/Internal/CertificateExtensions.cs
  AppService.Acmebot/Internal/WebhookClient.cs
  AppService.Acmebot/PurgeCertificatesFunctions.cs
  AppService.Acmebot/PurgeInstanceHistoryFunctions.cs
  AppService.Acmebot/RenewCertificatesFunctions.cs
  AppService.Acmebot/SharedFunctions.cs
Labels: bug

#208 Adding support to Azure Government and China
  AppService.Acmebot/GetSitesFunctions.cs
  AppService.Acmebot/Internal/AcmeProtocolClientFactory.cs
  AppService.Acmebot/Internal/AppAuthenticationTokenProvider.cs
  AppService.Acmebot/Internal/AzureEnvironment.cs
  AppService.Acmebot/Internal/WebhookClient.cs
  AppService.Acmebot/Options/AcmebotOptions.cs
  AppService.Acmebot/SharedFunctions.cs
  AppService.Acmebot/Startup.cs
  README.md
  azuredeploy.json
Labels: enhancement

#210 Modify to run the ARM API on a per-resource group
  AppService.Acmebot/AppService.Acmebot.csproj
  AppService.Acmebot/Contracts/ISharedFunctions.cs
  AppService.Acmebot/GetResourceGroupsFunctions.cs
  AppService.Acmebot/GetSitesFunctions.cs
  AppService.Acmebot/Internal/AzureSdkExtensions.cs
  AppService.Acmebot/Internal/CertificateExtensions.cs
  AppService.Acmebot/Models/GetSitesInformation.cs
  AppService.Acmebot/PurgeCertificatesFunctions.cs
  AppService.Acmebot/RenewCertificatesFunctions.cs
  AppService.Acmebot/SharedFunctions.cs
  AppService.Acmebot/Startup.cs
  AppService.Acmebot/static/add-certificate.html
Labels: enhancement

#212 Fixed app service name sort
  AppService.Acmebot/GetResourceGroupsFunctions.cs
  AppService.Acmebot/SharedFunctions.cs
Labels: enhancement

#216 Update README.md
  README.md
Labels: documentation

#217 Update DurableTask v2.3.0
  AppService.Acmebot/AppService.Acmebot.csproj
Labels: enhancement

#219 Update Durable Task Proxy
  AppService.Acmebot/AppService.Acmebot.csproj
Labels: bug
