Repository shibayan/appservice-acmebot, pull requests merged in 2020-05, with the labels that each got.

#157 Supoort IDN certificate
  AppService.Acmebot/AddCertificateFunctions.cs
  AppService.Acmebot/Internal/Punycode.cs
  AppService.Acmebot/RenewCertificatesFunctions.cs
  AppService.Acmebot/SharedFunctions.cs
Labels: bug

#158 Support for other ACME certification authorities
  AppService.Acmebot/AcmebotOptions.cs
  AppService.Acmebot/AppService.Acmebot.csproj
  AppService.Acmebot/Internal/AcmeProtocolClientFactory.cs
  AppService.Acmebot/Internal/WebhookLifeCycleNotification.cs
  AppService.Acmebot/Internal/X509Certificate2Extensions.cs
  AppService.Acmebot/Internal/X509Certificate2Helper.cs
  AppService.Acmebot/SharedFunctions.cs
  AppService.Acmebot/Startup.cs
  azuredeploy.json
Labels: enhancement

#159 Adding issuer tag to certificates
  AppService.Acmebot/Internal/KuduApiClientFactory.cs
  AppService.Acmebot/Internal/KuduClient.cs
  AppService.Acmebot/Internal/KuduClientFactory.cs
  AppService.Acmebot/SharedFunctions.cs
  AppService.Acmebot/Startup.cs
Labels: enhancement

#160 Migrate to GitHub Actions
  .github/workflows/build.yml
  .github/workflows/publish.yml
  README.md
  azure-pipelines.yml
Labels: enhancement

#163 Add troubleshooting steps for CheckDnsChallenge
  README.md
Labels: documentation

#164 Fixed Function runtime v3 error
  AppService.Acmebot/SharedFunctions.cs
  AppService.Acmebot/proxies.json
Labels: bug

#165 Refactoring issue certificate orchestrator
  AppService.Acmebot/AddCertificateFunctions.cs
  AppService.Acmebot/AppService.Acmebot.csproj
  AppService.Acmebot/RenewCertificatesFunctions.cs
  AppService.Acmebot/SharedFunctions.cs
Labels: enhancement

#167 Adding troubleshooting
  README.md
Labels: documentation

#168 Update Durable Functions
  AppService.Acmebot/AppService.Acmebot.csproj
Labels: enhancement

#169 Rename from domains to dnsNames
  AppService.Acmebot/AddCertificateFunctions.cs
  AppService.Acmebot/Contracts/ISharedFunctions.cs
  AppService.Acmebot/GetSitesFunctions.cs
  AppService.Acmebot/Models/AddCertificateRequest.cs
  AppService.Acmebot/Models/GetSitesInformation.cs
  AppService.Acmebot/RenewCertificatesFunctions.cs
  AppService.Acmebot/SharedFunctions.cs
  AppService.Acmebot/index.html
Labels: enhancement
